# Generated by Django 4.1.3 on 2022-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contecttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contecttable',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
