# Generated by Django 4.1.3 on 2022-11-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_contecttable_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='images/Screenshot.png', null=True, upload_to=''),
        ),
    ]
