# Generated by Django 4.1.3 on 2022-11-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image1',
            field=models.ImageField(blank=True, default='images/Screenshot.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='content',
            name='image2',
            field=models.ImageField(blank=True, default='images/Screenshot.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='content',
            name='image3',
            field=models.ImageField(blank=True, default='images/Screenshot.png', null=True, upload_to=''),
        ),
    ]
