# Generated by Django 4.1.3 on 2022-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_content_image1_content_image2_content_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='Screenshot.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='image1',
            field=models.ImageField(blank=True, default='Screenshot.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='image2',
            field=models.ImageField(blank=True, default='Screenshot.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='image3',
            field=models.ImageField(blank=True, default='Screenshot.png', null=True, upload_to=''),
        ),
    ]
